export const SIGN_IN_EMAIL='SIGN_IN_EMAIL';
export const CREATE_USER_EMAIL_PASSWORD ='CREATE_USER_EMAIL_PASSWORD';
export const ADD_ERROR='ADD_ERROR';
export const SET_LOCATION ='SET_LOCATION';
export const GET_LOCATION_LISTENER='GET_LOCATION_LISTENER';
export const STOP_LOCATION_LISTENER='STOP_LOCATION_LISTENER';